import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
import math
import a_star
import numpy as np



'''Creation of synthetic map'''
map = np.array([[0, 1, 0, 0, 0, 0],
                [0, 1, 0, 1, 0, 0],
                [0, 0, 0, 1, 0, 0],
                [1, 1, 0, 0, 0, 0],
                [0, 0, 1, 0, 0, 0],
                [0, 0, 1, 0, 0, 0]])

start_node = np.array([0, 0])
goal_node = np.array([5, 5])
rows, cols = map.shape
''''''


class RobotControl(Node):
    '''Realisation of movement in a maze'''
    def __init__(self, path):
        super().__init__('a_star_node')
        
        # path generated by A* algorithm
        self.path = path
        self.near_target_position = 0.2

        # counter of current position
        self.pos_idx = 0

        self.x_target = float(self.path[self.pos_idx][0])
        self.y_target = float(self.path[self.pos_idx][1])

        # init current robot positions
        self.x = 0.0
        self.y = 0.0
        self.theta = 0.0
        self.pose_received = False # check if robot reach target point
        
        self.trajectory_x = []
        self.trajectory_y = []

        self.k_v = 0.5 
        self.k_s = 2.0

        # publisher of velocities
        self.publisher = self.create_publisher(Twist, '/cmd_vel', 10)
        # subscriber of odometry - current position
        self.subscription = self.create_subscription(Odometry, '/odom', self.subscribeOdom, 10)
        
        self.timer = self.create_timer(0.1, self.publishVel)
        
        self.get_logger().info(f"Target point ({self.x_target}, {self.y_target})")

    def subscribeOdom(self, msg):
        '''Getting current position'''
        self.x = msg.pose.pose.position.x
        self.y = msg.pose.pose.position.y

        self.trajectory_x.append(self.x)
        self.trajectory_y.append(self.y)
        
        qz = msg.pose.pose.orientation.z
        qw = msg.pose.pose.orientation.w
        self.theta = 2.0 * math.atan2(qz, qw)
        
        self.pose_received = True # flag of reaching target point

    def publishVel(self):
        '''Publish velocities'''
        if not self.pose_received:
            return
        
        dx = self.x_target - self.x
        dy = self.y_target - self.y
        distance = math.sqrt(dx**2 + dy**2)
        
        msg = Twist()
        
        if distance < self.near_target_position:
            self.pos_idx += 1
            if self.pos_idx >= len(self.path):

                self.get_logger().info("Arrived to goal point")
                self.publisher.publish(msg)
                raise SystemExit
            else:
                self.x_target = float(self.path[self.pos_idx][0])
                self.y_target = float(self.path[self.pos_idx][1])
                self.get_logger().info("Next target point: ({self.x_target}, {self.y_target})")
                self.publisher.publish(msg)
                return
        
        # error of angle
        angle = math.atan2(dy, dx) - self.theta
        angle_norm = math.atan2(math.sin(angle), math.cos(angle))
        
        msg.angular.z = self.k_s * angle_norm

        # x is a direction of robot's front
        msg.linear.x = min(self.k_v * distance, 0.22) # limit of max speed
            
        self.publisher.publish(msg)



def main(args=None):
    path = a_star.a_star(map, start_node, goal_node)

    rclpy.init(args=args)

    robot1 = RobotControl(path)

    try:
        rclpy.spin(robot1)
    except KeyboardInterrupt:
        robot1.get_logger().info("Program stopped")
    finally:
        stop_msg = Twist()
        robot1.publisher.publish(stop_msg)
        robot1.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()